#!/usr/bin/env python3

#  -*- python -*-

import re

# regex101.com

class Line:
    def __init__(self):
        pass

def parseLine(inFd):
    line = inFd.readline()
    print(line)


def main():
    filename = "fig2.1.asm"

    with open(filename, "r") as infile:
        parseLine(infile)

if __name__ == "__main__":
    main()
